### PR TITLE
Issue 41: Update langkit

### LINKED ISSUE #41: Update to latest langkit without new DSL

### PR DESCRIPTION
**Pull request by jklmnn**
Closes #41

### CODE REVIEW

**Review by senier — COMMENTED** [review]
Now you only have to fix this little bug box :wink:

**Comment by jklmnn** [comment]
Let me guess, increasing the minimum required GNAT version is not an option, right?

**Comment by senier** [comment]
> Let me guess, increasing the minimum required GNAT version is not an option, right?

Before we do that, maybe we can identify the offending constructs / compiler options?

**Comment by jklmnn** [comment]
It seems this change introduces the problem: https://github.com/AdaCore/langkit/commit/5e76298076509a0c562d595e460e92977719623c
I'll ask the langkit guys what we can do about this but as it is langkit generated code I'm not sure how much we can change about it. The problem seems to be fixed with GNAT CE 2021.

**Comment by jklmnn** [comment]
I just discussed with @pmderodat. The code that initially introduced this problem is going to be removed in 2 -3 weeks. I don't think it makes sense to try to fix this issue until then. Alternatively we could drop support for GNAT CE 2020, given that GNAT CE 2021 is freely available.

**Comment by treiher** [comment]
In this case, I would favor waiting for 2-3 weeks. I think the usability is better, if we support the same set of compilers for installing RecordFlux as for compiling RecordFlux´ generated code.

**Pull request closed without merging**
